version: '2'

services:
  auth-app:
#    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ../life-helper-authentication-service
      dockerfile: ./Dockerfile
    container_name: auth-app
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/life_helper_auth
      - DB_USERNAME=nikitadmitrenko
      - DB_PASSWORD=
      - JWT_SECRET_ACCESS=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      - JWT_SECRET_REFRESH=zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
      - JWT_EXPIRATION_MINUTES=25
      - JWT_EXPIRATION_DAYS=30
    ports:
      - "8030:8030"
    networks:
      - rmoff_kafka

  user-app:
    build:
      context: .
    container_name: user-app
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/life_helper_user #host.docker.internal для подключения к внешней бд
      - DB_USERNAME=nikitadmitrenko
      - DB_PASSWORD=
      - JWT_SECRET_ACCESS=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    ports:
      - "8031:8031"
    networks:
      - rmoff_kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    networks:
      - rmoff_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  rmoff_kafka:

